# Download git repository with my config files
- name: Clone the repository 
  git:
    repo: https://gitlab.com/kazyklas/linux.git
    dest: /home/ubuntu/Documents

########################################################################
# Create the folders for the config files 
########################################################################

- name: Create folder for terminator
  file:
    path: /home/ubuntu/.config/terminator
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: '0777'


- name: Create folder for i3
  file:
    path: /home/ubuntu/.config/i3
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: '0777'


########################################################################
# Copy config files to the desired directories
########################################################################

- name: Copy config files for terminator
  copy:
    src: /home/ubuntu/Documents/linux/config/terminator/config
    dest: /home/ubuntu/.config/terminator/config
    remote_src: yes

- name: Copy config files for i3 
  copy:
    src: /home/ubuntu/Documents/Gitlab/linux/config/i3 
    dest: /home/ubuntu/.config/i3
    remote_src: yes


########################################################################
# Copy dotfiles to the system
########################################################################

- name: Copy .vimrc
  copy:
    src: /home/ubuntu/Documets/linux/dotfiles/*
    dest: /home/ubuntu
    remote_src: yes

