# Download git repository with my config files
- name: Clone the repository 
  git:
    repo: https://gitlab.com/kazyklas/linux.git
    dest: /home/ubuntu/Documents

- name: Create folder for terminator
  file:
    path: /home/ubuntu/.config/terminator
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: '0777'

- name: Copy config files for terminator
  copy:
    src: /home/ubuntu/Documents/Gitlab/linux/config/terminator/config
    dest: /home/ubuntu/.config/terminator/config
    remote_src: yes

- name: Copy config files for i3 
  copy:
    src: /home/ubuntu/Documents/Gitlab/linux/config/i3 
    dest: /home/ubuntu/.config/i3
    remote_src: yes

    #- name: Copy .vimrc
    #  copy:
    #    src: /home/ubuntu/Documets/Gitlab/linux/dotfiles/.vimrc
    #    dest: /home/ubuntu
    #    remote_src: yes

- name: Install pathogen for vim
  shell: mkdir -p ~/.vim/autoload ~/.vim/bundle && curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim
