# Deploy to the hosts in inventory

- hosts: all
  # speed up deployment and forbid gathering unnecesary stuff
  
  vars:
    - apt_file: /etc/apt/sources.list.d/google-chrome.list

  gather_facts: false
  tasks:
    - name: Gather required facts facts
      setup:
      
    - include: tasks/install-packages.yml

    - include: tasks/configure-system.yml

